from enum import Enum


class State(Enum):

    SMALL_TALK = 0

    ADD_NEW_QUEST = 1
    ACTIVATE_QUEST = 2
    SHEDULE_QUEST_NAME = 3
    SHEDULE_QUEST_DATE = 3.5

    DELETE_QUEST = 4
    DELETE_PANDORA_QUEST = 5
    DELETE_SERIF_WALL_QUEST = 6

    RETURN_QUEST = 7
    RETURN_PANDORA_QUEST = 8
    RETURN_SERIF_WALL_QUEST = 9

    CLOSE_QUEST = 10
    CLOSE_PANDORA_QUEST = 11
    CLOSE_SERIF_WALL_QUEST = 12

    GET_STATISTIC = 13
    GET_QUESTS = 14
